package data.database.impl.core.database

import androidx.room.Database
import androidx.room.RoomDatabase
import data.database.api.source.resource.ApplicationDatabase
import data.database.impl.core.database.RoomDatabase.Companion.VERSION
import data.database.impl.source.dao.ApplicationDao

/**
 * The Room database for the application.
 *
 * This is the single Room database instance for the entire app. It declares all
 * entities and exposes abstract DAO accessor methods that Room generates at compile time.
 *
 * Schema export is enabled (`exportSchema = true`) so Room writes JSON schema files
 * for each version, enabling migration validation.
 *
 * @see ApplicationDatabase
 * @see ApplicationDao
 * @see data.database.impl.di.DataDatabaseImplModule
 * @since 0.0.1
 */
@Database(
    version = VERSION,
    entities = [
        ApplicationDatabase::class,
    ],
    exportSchema = true,
)
public abstract class RoomDatabase : RoomDatabase() {
    /**
     * Gets the DAO for [ApplicationDatabase] entities.
     *
     * @return The [ApplicationDao] instance generated by Room.
     * @see ApplicationDao
     */
    public abstract fun getApplicationDao(): ApplicationDao

    /**
     * Companion object holding database-level constants.
     *
     * @since 0.0.1
     */
    public companion object {
        /**
         * The current database schema version.
         *
         * Increment this value whenever the schema changes and provide
         * a corresponding [Migration][androidx.room.migration.Migration].
         */
        public const val VERSION: Int = 1
    }
}
