package data.database.impl.di

import android.content.Context
import androidx.room.Room
import data.database.api.core.configure.DatabaseConfigure
import data.database.impl.core.database.RoomDatabase
import data.database.impl.source.dao.ApplicationDao
import org.koin.core.annotation.ComponentScan
import org.koin.core.annotation.Module
import org.koin.core.annotation.Single

/**
 * Koin module providing database instances and DAOs for the `data-database-impl` layer.
 *
 * Annotated with [ComponentScan] so that KSP automatically discovers and registers
 * all Koin-annotated classes under the `data.database.impl` package (e.g.,
 * [ApplicationDatabaseSourceImpl][data.database.impl.source.datasource.ApplicationDatabaseSourceImpl]).
 *
 * @see RoomDatabase
 * @see ApplicationDao
 * @since 0.0.1
 */
@Module
@ComponentScan("data.database.impl")
public class DataDatabaseImplModule {
    /**
     * Provides the singleton [RoomDatabase] instance built with the application [Context].
     *
     * The database file is named according to [DatabaseConfigure.DATABASE].
     * Destructive migration fallback is **disabled** (`false`), so a missing migration
     * will throw an [IllegalStateException] rather than silently dropping tables.
     *
     * @param appContext The application context required to build the database.
     * @return The application's Room database.
     * @see DatabaseConfigure.DATABASE
     */
    @Single
    public fun providesAppDatabase(appContext: Context): RoomDatabase {
        return Room
            .databaseBuilder(
                appContext,
                RoomDatabase::class.java,
                DatabaseConfigure.DATABASE,
            )
            // Disabling destructive migration forces explicit Migration objects for schema changes.
            .fallbackToDestructiveMigration(false)
            .build()
    }

    /**
     * Provides the singleton [ApplicationDao] instance extracted from the [RoomDatabase].
     *
     * @param database The Room database instance.
     * @return The application DAO generated by Room.
     * @see RoomDatabase.getApplicationDao
     */
    @Single
    public fun provideApplicationDao(database: RoomDatabase): ApplicationDao {
        return database.getApplicationDao()
    }
}
